### ISSUE TITLE
Add CI (travis?)

### ISSUE THREAD

**Issue by kevmoo** [google/dart-basics#17]
Add me as a maintainer and I'm happy to take care of it...I have a lot of experience!

https://travis-ci.org/github/kevmoo 😄

**Comment by kevmoo** [comment]
cc @johnsonmh

**Comment by johnsonmh** [comment]
Thanks for filing! We currently have CI set up through GitHub Actions https://github.com/google/dart-basics/blob/master/.github/workflows/dart.yml

Right now it does a pub get and runs the tests

**Comment by kevmoo** [comment]
okay!
