### ISSUE TITLE
[NNBD] Remove "Optional"s in favor of nullable types when dart is NNBD

### ISSUE THREAD

**Issue by johnsonmh** [google/dart-basics#20]
Right now `iterable_basics.dart` has some methods that return `Optional`s. Once Dart has non-nullable types by default, we should return nullable types instead of Optionals.

NNBD = Non-null by default.

**Comment by jamesderlin** [comment]
I think this also was already done by @zdg2102 in 9348225.

**Comment by zdg2102** [comment]
Yep, I'll close this issue once I get that checked in (currently still fighting some pubspec issues)

**Comment by zdg2102** [comment]
NNBD PR is checked in now, so I'm closing this.
