### ISSUE TITLE
Add whereKey, whereValue, whereKeyValue on Iterable<MapEntry>

### ISSUE THREAD

**Issue by marcelgarus** [google/dart-basics#22]
Dealing with `MapEntry`s is cumbersome:

```dart
final differentChunks = _newChunks.entries
        .where((entry) => entry.value.isDirty)
        .where((entry) => entry.value.data != _originalChunks[entry.key])
        .toList();
```

Extension methods for `whereKey`, `whereValue` and `whereKeyValue` on `Iterable<MapEntry<K, V>>` could make this much more readable:

```dart
final differentChunks = _newChunks.entries
        .whereValue((chunk) => chunk.isDirty)
        .whereKeyValue((index, chunk) => chunk.data != _originalChunks[index])
        .toList();
```

> Code context: I have a `List` of data chunks and a `List` of possibly changed data chunks, which have an `isDirty` property to indicate whether some values were changed. It's possible that some data is changed and then changed back again, so to get a `List` of only those chunks that are actually different than the other, I first filter by the `isDirty` property and only then do the expensive comparison of actual values.

**Comment by marcelgarus** [comment]
Come to think of it, `keys` and `value` getters would also be very helpful.

**Comment by johnsonmh** [comment]
This an interesting idea, personally I feel like it might make more sense as an extension of `Map` rather than `Iterable<MapEntry>`. 

Would something like this be similarly useful? 

```dart
void main() {
  print({1: 2, 3: 5, 6: 7}.whereKey((key) => key % 2 == 0));
  // Returns {6: 7}
}

extension Foo on Map {
  Map whereKey<K, V>(bool Function(K) callback) {
    return Map.fromEntries(this.entries.where((entry) => callback(entry.key)));
  }
}

```

**Comment by marcelgarus** [comment]
Yes, that would also solve what I'm trying to do. 👌
And because `Map` already has `keys` and `values` getters, they wouldn't need to be implemented anymore.
