### ISSUE TITLE
Null safety

### ISSUE THREAD

**Issue by TimWhiting** [google/dart-basics#33]
Is the null-safe version going to be published soon?

**Comment by behnamsattar** [comment]
Please consider publishing null safety support as there are many packages relying on this package!

**Comment by Medosopher** [comment]
The code seems to be ready to be null safe. What's the hold-up?

**Comment by deadsoul44** [comment]
Any update?

**Comment by johnsonmh** [comment]
Hi all, thanks for the reminders, version `0.6.0` is now live on [pub.dev](https://pub.dev/packages/basics)
