### ISSUE TITLE
Question on changes on done as part of null safety release

### ISSUE THREAD

**Issue by MaikuB** [google/dart-basics#35]
Before the null safety release, the package relied on quiver for some APIs. For example `isBlank` was would call https://pub.dev/documentation/quiver/latest/quiver.strings/isBlank.html. This allowed passing a nullable string as `isBlank` would return true if it was null or only contained whitespace characters. With this [PR](https://github.com/google/dart-basics/pull/24) from @zdg2102 to migrate the null safety this API other similar ones no longer accept nullable strings. This mean previously when developers were able to write

```
if(someString.isBlank) {
...
}
```

they now need to write

```
if(someString?.isBlank ?? true) {
...
}
```

I wanted to ask if this is an intentional change as this makes the library less useful in dealing with scenarios like this. Seems like something that perhaps should've been documented in the changelog as well but there's no mention of this. No unit tests exist for this API to have caught this change too

**Comment by zdg2102** [comment]
Yeah, good catch, the behavior regression was an accident unfortunately. The latest version adds `isNullOrBlank` and its inverse, which restores the old behavior, and should fix the example you have here. I also added some tests which should prevent an equivalent regression in the future.
